version: '2.2'
services:
    server:
        container_name: snapcast_server_main
        volumes:
            - '/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket'
        network_mode: host # easier than doing ports
        environment:
            - chunk_ms=30
            - buffer=1000
            - host=gworker # replace with host
        image: 'gtstef/snapserver'
        #image: 'gtstef/snapserver:0.3.3' # optional - build locally instead
        #build:
        #    context: ./snapserver
        #    dockerfile: dockerfile
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:1780"]
            timeout: 5s
            retries: 3
    cleanup_agent:
        container_name: snapcast_server_cleanup_agent
        depends_on:
            server:
                condition: service_healthy
        environment:
            - host=gworker
        network_mode: host
        image: 'gtstef/snapserver-cleanup-agent' # optional - build locally instead
        #build:
        #    context: ./snapserver
        #    dockerfile: dockerfile.cleanup
        restart: unless-stopped
# First bluetooth device - depnds on server
    client-kitchen:
        depends_on:
            server:
                condition: service_healthy
        hostname: kitchen
        container_name: snapcast_client_kitchen-bt
        restart: 'on-failure:3'
        volumes:
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - DEVICE="A4:05:0A:19:90:16"
            - host=gworker
            - instance=1
            - server=gworker
            - USE_STEREO=false
            - AUDIO_LATENCY=120 #  buffer/latency (each bt is diff)
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 10s
            retries: 3
        image: 'gtstef/snapclient'
        #build:
        #    context: ./snapclient
        #    dockerfile: dockerfile

    tv:
        depends_on:
            server:
                condition: service_healthy
        hostname: tv
        container_name: snapcast_client_tv
        restart: 'on-failure:3'
        volumes:
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - host=gworker
            - instance=2
            - server=gworker
            - USE_STEREO=false
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 5s
            retries: 1
        image: 'gtstef/snapclient'
        #image: 'gtstef/snapclient:0.3.0' # optional - build locally instead
        #build:
        #    context: ./snapclient
        #    dockerfile: dockerfile
