version: '2.2'
services:

    server:
        volumes:
            - '/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket'
        network_mode: host # easier than doing ports
        environment:
            - chunk_ms=30
            - buffer=1000
            - host=gworker # replace with host
        #image: 'gtstef/snapserver:0.3.3' # optional - build locally instead
        build:
            context: ./snapserver
            dockerfile: dockerfile
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:1780"]
            timeout: 5s
            retries: 3

    cleanup_agent:
        depends_on:
            server:
                condition: service_healthy
        environment:
            - host=gworker
        network_mode: host
        #image: 'gtstef/snapserver-cleanup-agent' # optional - build locally instead
        build:
            context: ./snapserver
            dockerfile: dockerfile.cleanup
        restart: unless-stopped

# First bluetooth device - depnds on server
    client-kitchen:
        depends_on:
            server:
                condition: service_healthy
        hostname: kitchen
        container_name: kitchen
        restart: 'on-failure:3'
        volumes:
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - DEVICE="A4:05:0A:19:90:16"
            - host=gworker
            - instance=1
            - server=gworker
            - USE_STEREO=false
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 10s
            retries: 3
        #image: 'gtstef/snapclient:0.3.0' # optional - build locally instead
        build:
            context: ./snapclient
            dockerfile: dockerfile

# Second bluetooth device - depnds on first bluetooth device!
# if you try to pair two bluetooth devices at the same time... you get failure.
    client-bedroom:
        depends_on:
            client-kitchen:
                condition: service_healthy
        hostname: bedroom
        container_name: bedroom
        restart: 'on-failure:3'
        volumes:
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - DEVICE="F5:63:4B:0F:D4:8F"
            - host=gworker # enter your own hostname
            - instance=3  # make sure unique number - no other clients have!
            - server=gworker # enter your own hostname
            - USE_STEREO=false # if you want mono bluetooth
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 10s
            retries: 3
        #image: 'gtstef/snapclient:0.3.0' # optional - build locally instead
        build:
            context: ./snapclient
            dockerfile: dockerfile

    tv:
        depends_on:
            server:
                condition: service_healthy
        hostname: tv
        container_name: tv
        restart: 'on-failure:3'
        volumes:
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - host=gworker
            - instance=2
            - server=gworker
            - USE_STEREO=false
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 5s
            retries: 1
        #image: 'gtstef/snapclient:0.3.0' # optional - build locally instead
        build:
            context: ./snapclient
            dockerfile: dockerfile
