# Build librespot with cargo in builder stage
# Note: currently not compatible with arm32

FROM rust:slim-bullseye AS builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y install build-essential pkg-config curl

ARG LIBRESPOT_VERSION=0.4.2

RUN cargo install librespot --version "${LIBRESPOT_VERSION}" --no-default-features

# Install snapcast and copy librespot binary from builder stage
FROM ubuntu
COPY --from=builder /usr/local/cargo/bin/librespot /usr/local/bin/
