version: '3.6' # warning: requires recent version of docker-compose
services:
    server:
        volumes:
            - '/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket'
            - '/var/run/dbus:/var/run/dbus'
        network_mode: host
        environment:
            - chunk_ms=30
            - buffer=1000
        image: 'gtstef/snapserver'
        restart: "no"
    cleanupAgent:
        depends_on: [server]
        network_mode: host
        image: 'gtstef/snapserver-cleanup-agent'
        restart: "unless-stopped"
# First bluetooth device - depnds on server
    kitchenSpeaker:
        network_mode: host
        depends_on: [server]
        hostname: kitchen
        restart: "no"
        volumes:
            - '/var/run/dbus:/var/run/dbus'
            - '/usr/share/dbus-1:/usr/share/dbus-1'
        devices:
            - /dev/snd
        privileged: true
        privileged: true
        environment:
            - DEVICE="A4:05:0A:19:90:16"
            - instance=1
            - server=gworker.ghome.net
            - USE_STEREO=false
            - LATENCY=120 #  buffer/latency (each bt is diff)
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 10s
            retries: 3
        image: 'gtstef/snapclient'
        #build:
        #    context: ./snapclient
        #    dockerfile: dockerfile
# Second bluetooth device - depnds on first bluetooth device!
# Two bluetooth devices on one host requires BT 5.0 host module.
# Only certain devices support this, eg raspberry pi 4
    bedroomSpeaker:
        network_mode: host
        depends_on: [server]
        hostname: bedroom
        volumes:
            - '/usr/share/dbus-1:/usr/share/dbus-1'
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - DEVICE="F5:63:4B:0F:D4:8F"
            - instance=3  # make sure unique number - no other clients have!
            - server=gworker # enter your own hostname or eliminate this line if using snapserver from this config
            - USE_STEREO=false # if you want mono bluetooth
            - AUDIO_LATENCY=120 #  buffer/latency (each bt is diff)
        image: 'gtstef/snapclient'
        #build:
        #    context: ./snapclient
        #    dockerfile: dockerfile
    tvSpeaker:
        network_mode: host
        depends_on: [server]
        hostname: tv
        restart: "no"
        volumes:
            - '/var/run/dbus:/var/run/dbus'
        devices:
            - /dev/snd
        privileged: true
        environment:
            - instance=2
            - server=gworker
            - USE_STEREO=true
        healthcheck:
            test: ["CMD", "pgrep", "-f", "snapclient"]
            timeout: 5s
            retries: 1
        image: 'gtstef/snapclient'
        #build:
        #    context: ./snapclient
        #    dockerfile: dockerfile
