FROM gtstef/librespot:0.4.2 as librespot
FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN printf '#!/bin/sh\nexit 0' >/usr/sbin/policy-rc.d
RUN apt update && apt install -y \
    libavahi-client-dev \
    avahi-daemon \
    mdp \
    snapserver \
    curl

WORKDIR /opt
COPY --from=librespot /usr/local/bin/ /usr/local/bin/
COPY src .
RUN chmod 777 -R /opt/mpd
RUN chmod +x run.sh
ENTRYPOINT ["./run.sh"]