version: '2.2'
services:
    server:
        container_name: snapcast_server_main
        volumes:
            - '/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket'
        network_mode: host # easier than doing ports
        environment:
            - chunk_ms=30
            - buffer=1000
            - host=gworker # replace with host
        image: 'gtstef/snapserver'
        #image: 'gtstef/snapserver:0.3.3' # optional - build locally instead
        #build:
        #    context: ./snapserver
        #    dockerfile: dockerfile
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:1780"]
            timeout: 5s
            retries: 3
    cleanup_agent:
        container_name: snapcast_server_cleanup_agent
        depends_on:
            server:
                condition: service_healthy
        environment:
            - host=gworker
        network_mode: host
        image: 'gtstef/snapserver-cleanup-agent' # optional - build locally instead
        #build:
        #    context: ./snapserver
        #    dockerfile: dockerfile.cleanup
        restart: unless-stopped
