FROM alpine:3.16
WORKDIR /opt
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing librespot snapcast-server bash mpd
COPY src .
RUN chmod 777 -R /opt/mpd
RUN chmod +x run.sh

ENTRYPOINT ["./run.sh"]
