# This has annoying bug where it segfaults and causes awful noise. Will be fixed in snapserver 0.27
# https://github.com/badaix/snapcast/issues/1026
FROM alpine:edge
WORKDIR /opt
RUN apk add --no-cache \
        snapcast-server \
        bash \
        mpd \
        avahi \
        curl
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        librespot
COPY src .
RUN chmod 777 -R /opt/mpd
RUN chmod +x run.sh

ENTRYPOINT ["./run.sh"]
