FROM tmigone/librespot:0.3.1 as librespot
FROM alpine:edge
WORKDIR /opt
RUN apk add --no-cache \
        snapcast-server \
        curl \
        mpd
COPY --from=librespot /usr/bin/librespot /usr/local/bin/
COPY src .
RUN chmod 777 -R /opt/mpd
RUN chmod +x run.sh
ENTRYPOINT ["./run.sh"]