FROM gtstef/snapbase as base
FROM ubuntu:21.04

# To avoid problems with Dialog and curses wizards
ENV DEBIAN_FRONTEND noninteractive
RUN printf '#!/bin/sh\nexit 0' >/usr/sbin/policy-rc.d

# Define a user under which the pulseaudio server will be running
ENV USER pulseaudio
ENV UID 1000
ENV GROUPS audio
ENV HOME /home/$USER
RUN apt update && apt install -y procps netcat curl \
    pulseaudio pulseaudio-module-bluetooth bluez alsa-utils \
    libavahi-client-dev libbluetooth3 expect sudo && \
    apt clean && rm -rf /var/lib/apt/lists

RUN useradd -u $UID -m -d $HOME -s /usr/sbin/nologin $USER && \
    usermod -aG $GROUPS $USER && \
    chmod 0655 -- /etc/pulse/* && \
    mkdir -p $HOME/.config/pulse && \
    chown -Rh $USER:$USER -- $HOME && \
    echo "$USER:x:${uid}:${gid}:$USER,,,:/home/$USER:/bin/bash" >>/etc/passwd && \
    echo "$USER:x:${uid}:" >>/etc/group && \
    mkdir -p /etc/sudoers.d && \
    echo "$USER ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/$USER && \
    chmod 0440 /etc/sudoers.d/$USER && \
    chsh -s /bin/bash $USER
USER $USER
WORKDIR $HOME

# copy snapclient
COPY --from=base --chown=root:$USER /opt/snapcast/client/snapclient /usr/bin/
RUN cd $HOME

COPY [ "src/.asoundrc*", "src/*.wav", "./" ]
COPY [ "src/main.conf", "src/audio.conf", "/etc/bluetooth/" ]
COPY [ "src/default.pa", "src/daemon.conf", "/etc/pulse/" ]

COPY src/snaprun.sh .
RUN sudo chmod +x snaprun.sh
RUN sudo chown $USER:$USER -R .
RUN sudo chown $USER:$USER /etc/pulse/daemon.conf

ENTRYPOINT ["./snaprun.sh"]
