version: '3.3'
services:
    kitchen:
        volumes:
            - '/var/run/dbus:/var/run/dbus'
            - '/dev/snd:/dev/snd'
        environment:
            - device=test
            - host=gworker
        privileged: true
        image: 'gtstef/snapclient:0.3.0'
    tv:
        network_mode: host
