FROM ubuntu:21.10
# To avoid problems with Dialog and curses wizards
ENV DEBIAN_FRONTEND noninteractive
RUN printf '#!/bin/sh\nexit 0' >/usr/sbin/policy-rc.d
RUN sed -i 's/ports.ubuntu.com\/ubuntu-ports/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list \
    && sed -i 's/archive.ubuntu/old-releases.ubuntu/g' /etc/apt/sources.list \
    && sed -i 's/security.ubuntu/old-releases.ubuntu/g' /etc/apt/sources.list
# Define a user under which the pulseaudio server will be running
ENV USER pulseaudio
ENV UID 1000
ENV GROUPS audio
ENV HOME /home/$USER
RUN apt update && apt install -y --no-install-recommends \
    procps netcat-traditional curl \
    pulseaudio pulseaudio-module-bluetooth bluez alsa-utils \
    libbluetooth3 expect sudo snapclient \
    && apt clean && rm -rf /var/lib/apt/lists

RUN useradd -u $UID -m -d $HOME -s /usr/sbin/nologin $USER && \
    usermod -aG $GROUPS $USER && \
    chmod 0655 -- /etc/pulse/* && \
    mkdir -p $HOME/.config/pulse && \
    chown -Rh $USER:$USER -- $HOME && \
    echo "$USER:x:${uid}:${gid}:$USER,,,:/home/$USER:/bin/bash" >>/etc/passwd && \
    echo "$USER:x:${uid}:" >>/etc/group && \
    mkdir -p /etc/sudoers.d && \
    echo "$USER ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/$USER && \
    chmod 0440 /etc/sudoers.d/$USER && \
    chsh -s /bin/bash $USER
USER $USER
WORKDIR $HOME

COPY --chown=$USER:$USER [ "src/.asoundrc*", "src/*.wav", "./" ]
COPY --chown=$USER:$USER [ "src/main.conf", "src/audio.conf", "/etc/bluetooth/" ]
COPY --chown=$USER:$USER [ "src/default.pa", "src/daemon.conf", "/etc/pulse/" ]
COPY --chown=$USER:$USER ["src/snaprun.sh", "./"]
RUN sudo chmod +x snaprun.sh

ENTRYPOINT ["./snaprun.sh"]
